# Generated by Django 5.0.6 on 2024-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_useraccount_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
