# Generated by Django 5.0.6 on 2024-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_useraccount_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
