# Generated by Django 5.0.7 on 2024-07-19 08:39

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_useraccount_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="password",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="accountPin",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="mobile",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[core.validators.validate_phone_number],
            ),
        ),
    ]
