# Generated by Django 5.0.7 on 2024-07-26 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pick1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draw_number', models.IntegerField(unique=True)),
                ('draw_name', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], max_length=1)),
                ('draw_date', models.DateField(auto_now_add=True)),
                ('draw_time', models.TimeField(auto_now_add=True)),
                ('draw_date_time', models.DateTimeField(auto_now_add=True)),
                ('game_date_time', models.DateTimeField()),
                ('is_draw_posted', models.BooleanField(default=False)),
                ('is_draw_approved', models.BooleanField(default=False)),
                ('is_draw_executed', models.BooleanField(default=False)),
                ('is_draw_execution_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['draw_number'], name='wager_pick1_draw_nu_5ded61_idx')],
            },
        ),
    ]
