# Generated by Django 5.0.7 on 2024-08-11 17:09

import django.db.models.deletion
import wager.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='placingPick1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.SmallIntegerField(validators=[wager.validators.pick_validation])),
                ('is_confirmed', models.BooleanField(default=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('draw_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placingpick1', to='wager.pick1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'draw_number')},
            },
        ),
    ]
