# Generated by Django 5.0.7 on 2024-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0003_alter_placingpick1_bet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placingpick1',
            name='bet_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
