# Generated by Django 5.0.7 on 2024-08-16 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0004_alter_placingpick1_bet_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='placingpick1',
            old_name='draw_number',
            new_name='draw_id',
        ),
        migrations.AlterUniqueTogether(
            name='placingpick1',
            unique_together={('user', 'draw_id')},
        ),
        migrations.AlterField(
            model_name='placingpick1',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placingPick1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='placingpick1',
            name='is_confirmed',
        ),
    ]
