# Generated by Django 5.0.7 on 2024-08-17 08:41

import django.db.models.deletion
import wager.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0005_rename_draw_number_placingpick1_draw_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_name', models.CharField(choices=[('P1', 'Pick 1'), ('P4', 'Pick 4')], max_length=2)),
                ('pick_number', models.SmallIntegerField(validators=[wager.validators.pick_validation])),
                ('bet_amount', models.PositiveIntegerField()),
                ('draw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placingpick1', to='wager.pick1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placingPick1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'draw_id')},
            },
        ),
        migrations.DeleteModel(
            name='placingPick1',
        ),
    ]
