# Generated by Django 5.0.7 on 2024-08-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0007_alter_customerwager_draw_id_alter_customerwager_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wager', to=settings.AUTH_USER_MODEL),
        ),
    ]
